service: apis-recognition-service

custom:
  OPENCV_PROCESS_BUCKET: client-image-upload
  OPENCV_OUTPUT_BUCKET: client-image-processing

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
         - 's3:ListBucket'
         - 's3:GetObject'
         - 's3:PutObject'
      Resource:
        - arn:aws:s3:::${self:custom.OPENCV_OUTPUT_BUCKET}/
        - arn:aws:s3:::${self:custom.OPENCV_PROCESS_BUCKET}/

functions:
 client_upload:
    handler: handler.client_upload
    events:
    - http:
        path: /client_upload
        method: post
    
 download_client_upload:
     handler: handler.download_client_upload
     events:
     - http:
         path: /download_client_upload
         method: get
     
 download_recognized:
      handler: handler.download_recognized
      events:
      - http:
          path: /download_recognized
          method: get
      
 delete_client_upload:
    handler: handler.delete_client_upload
    events:
    - http:
        path: /delete_client_upload
        method: delete
   
   
delete_recognized:
      handler: handler.delete_recognized
      events:
      - http:
          path: /delete_process
          method: delete
