Resources:
   # template de criação do autoscaling group
    ASGappFaceRecognition:
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateName: !Sub ASGappFaceRecognition
        LaunchTemplateData: 
          BlockDeviceMappings: 
            - Ebs:
                VolumeSize: 22
                VolumeType: gp2
                DeleteOnTermination: true
                Encrypted: true
              DeviceName: /dev/xvdcz
          CreditSpecification: 
            CpuCredits: Unlimited
          ImageId: ami-02354e95b39ca8dec
          InstanceType: t2.micro
          Monitoring: 
            Enabled: true
    CloudwatchLogsGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Join ['-', [ECSLogGroup, !Ref 'AWS::StackName']]
        RetentionInDays: 14
    taskdefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
        Family: !Join ['', [!Ref 'AWS::StackName', -ecs-demo-app]]
        ContainerDefinitions:
        - Name: simple-app
          Cpu: '10'
          Essential: 'true'
          Image: httpd:2.4
          Memory: '300'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'CloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs-demo-app
          MountPoints:
          - ContainerPath: /usr/local/apache2/htdocs
            SourceVolume: my-vol
          PortMappings:
          - ContainerPort: 80
        - Name: busybox
          Cpu: 10
          Command: ['sudo yum update -y', 
          'sudo amazon-linux-extras install docker',
          'sudo yum install docker',
          'sudo service docker start',
          'docker pull thiagothg/interface_facerecognition'
          ]
          EntryPoint: [sh, -c]
          Essential: false
          Image: busybox
          Memory: 200
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'CloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs-demo-app
          VolumesFrom:
          - SourceContainer: simple-app
        Volumes:
        - Name: my-vol


    ASGFaceRecognition:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AvailabilityZones: !GetAZs ''
        AutoScalingGroupName: ASG-apps-FaceRecognition
        MinSize: "1"
        MaxSize: "6"
        DesiredCapacity: "2"
        HealthCheckGracePeriod: 300
        LaunchTemplate:
          LaunchTemplateId: !Ref ASGappFaceRecognition
          Version: !GetAtt ASGappFaceRecognition.LatestVersionNumber
        MetricsCollection: 
          - Granularity: "1Minute"
            Metrics: 
              - "GroupMinSize"
              - "GroupMaxSize"
        Tags:
          - Key: Environment
            Value: Production
            PropagateAtLaunch: "true"
          - Key: Purpose
            Value: WebServerGroup
            PropagateAtLaunch: "false"
        
    WebSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable HTTP access via user defined port
        SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80